export const navs = [
  {
    link: '/about',
    name: 'About Us',
  },
  {
    link: '/services',
    name: 'Our Services',
    subpages: [
      { link: '/', name: 'All Services' },
      { link: '/ac-services', name: 'AC Services' },
      { link: '/auto-repair-estimates', name: 'Auto Repair Estimates' },
      { link: '/battery', name: 'Battery' },
      { link: '/bg', name: 'BG Services' },
      { link: '/brake-system', name: 'Brake System' },
      { link: '/check-engine-light', name: 'Check Engine Light' },
      { link: '/computer-diagnostics', name: 'Computer Diagnostics' },
      { link: '/drivetrain', name: 'Drivetrain' },
      { link: '/electrical-concerns', name: 'Electrical Concerns' },
      { link: '/engine-cooling-system', name: 'Engine Cooling System' },
      { link: '/engine-performance-repair', name: 'Engine Performance Repair' },
      { link: '/fleet-services', name: 'Fleet Services' },
      { link: '/fuel-system', name: 'Fuel System' },
      { link: '/hybrid-electric-vehicles', name: 'Hybrid/Electric Vehicles' },
      { link: '/pre-purchase-inspection', name: 'Pre-Purchase Inspections' },
      { link: '/courtesy-inspection', name: 'Courtesy Inspection' },
      { link: '/oil-and-filter-change', name: 'Oil and Filter Change' },
      { link: '/tune-ups', name: 'Tune-Ups' },
      { link: '/steering-components', name: 'Steering Components' },
      { link: '/suspension', name: 'Suspension' },
      { link: '/transmission', name: 'Transmission' },
    ],
  },
  {
    link: '',
    name: 'Luxury & Import Repair',
    subpages: [
      { link: '/mercedes', name: 'Mercedes' },
      { link: '/volkswagen', name: 'Volkswagen' },
      { link: '/acura', name: 'Acura' },
      { link: '/bmw', name: 'BMW' },
      { link: '/audi', name: 'Audi' },
      { link: '/volvo', name: 'Volvo' },
      { link: '/porsche', name: 'Porsche' },
      { link: '/land-rover', name: 'Land Rover' },
      { link: '/jaguar', name: 'Jaguar' },
      { link: '/buick', name: 'Buick' },
      { link: '/cadillac', name: 'Cadillac' },
      { link: '/infiniti', name: 'Infiniti' },
      { link: '/lexus', name: 'Lexus' },
      { link: '/mazda', name: 'Mazda' },
      { link: '/hyundai', name: 'Hyundai' },
    ],
  },
  { link: '/testimonials', name: 'Testimonials' },
  { link: '/contact#contact', name: 'Contact Us' },
];
